In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

Basic operation of array

In [4]:
print(a+b)
print(a-b)
print(a*b)

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]


In [5]:
## Creating a 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating 3D array
arr3 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[6,7,8]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
print(arr.shape)    #shape of the array

(2, 3)


In [8]:
print(arr.ndim)  #dimention of array


2


In [9]:
print(arr.dtype)

int64


In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,10)  # always go in left to right

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])